import {
  EasySideImg,
  Product1BannerImg,
  Product1BannerPhoneImg,
  Product1Img1,
  Product2BannerImg,
  Product2BannerPhoneImg,
  Product2Img,
  UniqueSideImg,
  Product4BannerImg,
  Product4Img,
  TrimWoodBg1,
  LineaVerticaImg1,
  LineaVerticaImg2,
  LineaVerticaImg3,
  LineaVerticaShade1,
  LineaVerticaShade2,
  LineaVerticaShade3,
  LineaLouverImg1,
  LineaLouverImg2,
  LineaLouverImg3,
  LineaLouverShade1,
  LineaLouverShade2,
  LineaLouverShade3,
  LineaSoffitImg1,
  LineaSoffitImg2,
  LineaSoffitImg3,
  LineaSoffitShade1,
  LineaSoffitShade3,
  LineaDuoImg1,
  LineaDuoImg2,
  LineaDuoImg3,
  LineaDuoShade1,
  LineaDuoShade2,
  LineaDuoShade3,
  DuraNormaImg1,
  DuraNormaImg2,
  DuraNormaImg3,
  DuraNormaShade1,
  DuraNormaShade2,
  DuraNormaShade3,
  DuraStrettaImg1,
  DuraStrettaImg2,
  DuraStrettaImg3,
  DuraStrettaShade1,
  DuraStrettaShade2,
  DuraStrettaShade3,
  EasyLineaImg1,
  EasyLineaImg2,
  EasyLineaImg3,
  EasyLineaShade1,
  EasyLineaShade2,
  EasyLineaShade3,
  EasyPyramidImg1,
  EasyPyramidImg2,
  EasyPyramidImg3,
  EasyPyramidShade1,
  EasyPyramidShade2,
  EasyPyramidShade3,
  Innov2WaveImg1,
  Innov2WaveImg2,
  Innov2WaveImg3,
  Innov2WaveShade1,
  Innov2WaveShade2,
  Innov2WaveShade3,
} from '../assets'

export const productsData = {
  2: {
    bannerSection: {
      bannerPhoneImg: Product1BannerPhoneImg,
      bannerImg: Product1BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN THE WORLD',
    },
    section1data: {
      mainImage: Product1Img1,
      sideImage: EasySideImg,
      techName: 'EASY+ TECHNOLOGY',
      techDesc:
        'This technology ensures quick, dust and dirt free installations. This technology ensures quick, dust and dirt free installations.',
      variants: 3,
    },
    section2data: [
      {
        type: 'Linea',
        desc: "Revitalize your space effortlessly with Easy+, the ultimate easy-to-install system, for remarkable transformations. Say goodbye to complicated installations and hello to stunning results with Easy+'s simplicity and convenience.",
        highlights: ['Easy to install', 'Recyclable', 'Advance Interlocking'],
        productImgs: [EasyLineaImg1, EasyLineaImg2, EasyLineaImg3],
        productShades: [EasyLineaShade1, EasyLineaShade2, EasyLineaShade3],
        pageLink: '/linea',
      },
      {
        type: 'Pyramid',
        desc: "Revitalize your space effortlessly with Easy+, the ultimate easy-to-install system, for remarkable transformations. Say goodbye to complicated installations and hello to stunning results with Easy+'s simplicity and convenience.",
        highlights: ['Easy to install', 'Anti-bacterial', 'Termite Proof & Rust Proof'],
        productImgs: [EasyPyramidImg1, EasyPyramidImg2, EasyPyramidImg3],
        productShades: [EasyPyramidShade1, EasyPyramidShade2, EasyPyramidShade3],
        pageLink: '/pyramid',
      },
      {
        type: 'Arch',
        desc: "Revitalize your space effortlessly with Easy+, the ultimate easy-to-install system, for remarkable transformations. Say goodbye to complicated installations and hello to stunning results with Easy+'s simplicity and convenience.",
        highlights: ['Easy to install', 'Advance Interlocking', 'No Ply required Can Be Screwed Directly on the walls'],
        productImgs: [EasyLineaImg1, EasyLineaImg2, EasyLineaImg3],
        productShades: [EasyLineaShade1, EasyLineaShade2, EasyLineaShade3],
        pageLink: '/arch',
      },
    ],
  },
  3: {
    bannerSection: {
      bannerPhoneImg: Product2BannerPhoneImg,
      bannerImg: Product2BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN INDIA',
    },
    section1data: {
      mainImage: Product2Img,
      sideImage: UniqueSideImg,
      techName: 'DURA+ TECHNOLOGY',
      techDesc:
        'Dura+ is the epitome of strength and durability for your exterior facade needs. With its robust construction and weather-resistant properties, Dura+ offers long-lasting protection and stunning aesthetics.',
      variants: 2,
    },
    section2data: [
      {
        type: 'Norma',
        desc: 'panels make you experience the perfect blend of durability and aesthetics with Norma. These decorative panels are meticulously crafted to provide a long-lasting solution for your exterior facades.',
        highlights: ['Superior Quality', 'Long Life', 'UV Resistant'],
        productImgs: [DuraNormaImg1, DuraNormaImg2, DuraNormaImg3],
        productShades: [DuraNormaShade1, DuraNormaShade2, DuraNormaShade3],
        pageLink: '/norma',
      },
      {
        type: 'Stretta',
        desc: 'panels help you achieve a flawless and refined look for your exterior wall cladding with Stretta. These panels boast a smooth and resilient surface, engineered to withstand scratches and impacts.',
        highlights: ['High Impact Resistance', 'Recyclable', 'Termite Proof & Rust Proof'],
        productImgs: [DuraStrettaImg1, DuraStrettaImg2, DuraStrettaImg3],
        productShades: [DuraStrettaShade1, DuraStrettaShade2, DuraStrettaShade3],
        pageLink: '/stretta',
      },
    ],
  },
  1: {
    bannerSection: {
      bannerPhoneImg: Product1BannerPhoneImg,
      bannerImg: Product1BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN INDIA',
    },
    section1data: {
      mainImage: Product1Img1,
      sideImage: UniqueSideImg,
      techName: 'INNOV+ TECHNOLOGY',
      techDesc:
        'Experience transformative spaces with Innov+, the ultimate wall and ceiling system. Enhance aesthetics and functionality seamlessly with cutting-edge innovation. Elevate your space and embrace the future of interior design.',
      variants: 4,
    },
    section2data: [
      {
        type: 'Duo',
        desc: "- India's first polymer-based wall and ceiling system. Easy installation, maintenance-free, waterproof, and fire retardant. Elevate your space with our versatile collections and enjoy a seamless, hassle-free solution.",
        highlights: ['Unique Interlocking', 'Fire Retardant', 'Light Weight'],
        productImgs: [LineaDuoImg1, LineaDuoImg2, LineaDuoImg3],
        productShades: [LineaDuoShade1, LineaDuoShade2, LineaDuoShade3],
        pageLink: '/duo',
      },
      {
        type: 'Soffit',
        desc: 'offer the visual appeal of real wood without the drawbacks. Enjoy quick and easy installation with a seamless finish, transforming your space effortlessly.',
        highlights: ['No VOC Emission', 'Waterproof', 'Real Wood Feel'],
        productImgs: [LineaSoffitImg1, LineaSoffitImg2, LineaSoffitImg3],
        productShades: [LineaSoffitShade1, LineaSoffitImg2, LineaSoffitShade3],
        pageLink: '/soffit',
      },
      {
        type: 'Louvers',
        desc: '- with their durability and waterproof features, they are perfect for various applications. The seamless interlocking system ensures a flawless finish, allowing them to integrate seamlessly with other PARÉ products.',
        highlights: ['Fire Retardant', 'Maintenance Free', '10 Years Warranty'],
        productImgs: [LineaLouverImg1, LineaLouverImg2, LineaLouverImg3],
        productShades: [LineaLouverShade1, LineaLouverShade2, LineaLouverShade3],
        pageLink: '/louvers',
      },
      {
        type: 'Vertica',
        desc: 'panels, the smart and easy-to-install solution for walls and ceilings. Experience a seamless and efficient installation process, while enjoying the benefits of low maintenance and reduced wastage.',
        highlights: ['Sleek Design', 'Impact Resistance', 'Unique Interlocking'],
        productImgs: [LineaVerticaImg1, LineaVerticaImg2, LineaVerticaImg3],
        productShades: [LineaVerticaShade1, LineaVerticaShade2, LineaVerticaShade3],
        pageLink: '/vertica',
      },
    ],
  },
  4: {
    bannerSection: {
      bannerPhoneImg: Product4BannerImg,
      bannerImg: Product4BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN THE WORLD',
    },
    section1data: {
      mainImage: Product4Img,
      sideImage: UniqueSideImg,
      techName: 'INNOV2+ TECHNOLOGY',
      techDesc:
        'Presenting Innov2+, an extraordinary fusion of innovation and excellence, poised to revolutionize your spaces with contemporary elegance and state-of-the-art functionality.',
      variants: 1,
    },
    section2data: [
      {
        type: 'Wave',
        desc: 'panels inspired by the graceful movement of ocean waves, these innovative panels add a touch of elegance and sophistication to any interior surfaces.',
        highlights: ['Easy to install', 'Recyclable', 'Advance Interlocking'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/wave',
      },
    ],
  },
}

// Blog Data
export const blogData = [
  {
    title: '5 Creative Ways to Incorporate Tiles into Your Interior Design',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 1,
  },
  {
    title: 'Expert Tips from Our Design Team',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 2,
  },
  {
    title: 'From Bold Patterns to Subtle Textures: Exploring the Versatility of Interior Design Tiles',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 3,
  },
  {
    title: 'Revamp Your Home with Unique and Beautiful Tile Designs: Our Top Picks',
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 4,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Design",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 5,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designs",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 6,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designss",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 7,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designsss",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 8,
  },
  {
    title: '5 Creative Ways to Incorporate Tiles into Your Interior Designsss',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 9,
  },
  {
    title: 'Expert Tips from Our Design Teams',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 10,
  },
  {
    title: 'From Bold Patterns to Subtle Textures: Exploring the Versatility of Interior Dessign Tiles',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 11,
  },
  {
    title: 'Revamp Your Home with Unique and Beautiful Tile Designs: Our Top Piicks',
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 12,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Deesign",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 13,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Dessign",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 14,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Innterior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 15,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Intterior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 16,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Inteerior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 17,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interiior Design",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 18,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interiorrr Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 19,
  },
]
